#  Copyright (c) 2015-2018 Patrick Diehl
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
version: 2

jobs:
    build:
    docker:
       - image: stellargroup/hpxcl:build_env
    working_directory: /hpx
    steps:
    - checkout
    - run: 
         name: Prepare build folder
         command: mkdir build && cd build
    - run: 
         name: Configure
         command: cmake .. -DCMAKE_BUILD_TYPE=Debug -DHPX_WITH_MALLOC=system -DCMAKE_CXX_FLAGS="-fcolor-diagnostics" -DHPXCL_WITH_OPENCL=On -DHPXCL_WITH_CUDA=On -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 -DHPXCL_WITH_BENCHMARK=On
    - run: make -j 2
    - save_cache:
        key: build-{{ .Branch }}-{{ .Revision }}
        paths:
            - "hpx/build"
    