#  Copyright (c) 2015-2021 Patrick Diehl
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
version: 2

jobs:
    build:
      docker:
          - image: fedora:33
      working_directory: /hpx/
      steps:
       - checkout
       - run:
           name: Install dependencies
           command: dnf update -y && dnf install -y  doxygen libpng-devel hpx-devel cmake
       - run: 
           name: Install cuda
           command: |
                dnf install -y  'dnf-command(config-manager)' && \
                dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora33/x86_64/cuda-fedora33.repo && \
                dnf clean expire-cache && \
                dnf update -y && \
                dnf module install -y  nvidia-driver:latest-dkms && \
                dnf install -y  cuda
       - run:
           name: Create build folder
           command: cd /hpx && mkdir -p build
       - run: 
           name: Configure
           command: cd /hpx/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DHPX_WITH_MALLOC=system -DHPXCL_WITH_OPENCL=OFF -DHPXCL_WITH_CUDA=On  -DHPXCL_WITH_BENCHMARK=On -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0
       - run: 
           name: Build
           command: cd /hpx/build && make -j 2
       - save_cache:
           key: build-{{ .Branch }}-{{ .Revision }}
           paths:
              - "/hpx"
    
    test:
      docker:
       - image: stellargroup/hpx:dev
      working_directory: /hpx/
      steps:
       - checkout
       - restore_cache:
          key:  build-{{ .Branch }}-{{ .Revision }}
       - run:
          name: Run tests
          command:  cd /hpx/build && ../tools/run_tests.sh
       
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                 - gh-pages
