// Copyright (c)       2014 Martin Stumpf
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#ifndef MANDELBROT_MANDELBROTKERNEL_H_
#define MANDELBROT_MANDELBROTKERNEL_H_

static const char* mandelbrot_kernels =
"                                                                            \n" 
"    #pragma OPENCL EXTENSION cl_khr_fp64 : enable                           \n"
"                                                                            \n"
"    float get_red_from_table(size_t id)                                     \n"
"    {                                                                       \n"
"                                                                            \n" 
"        switch(id)                                                          \n"
"        {                                                                   \n"
"            case    0: return  10.50000f;                                   \n"
"            case    1: return   3.15846f;                                   \n"
"            case    2: return   0.39901f;                                   \n"
"            case    3: return   0.50955f;                                   \n"
"            case    4: return   2.98021f;                                   \n"
"            case    5: return   7.85507f;                                   \n"
"            case    6: return  15.74049f;                                   \n"
"            case    7: return  27.02524f;                                   \n"
"            case    8: return  43.28563f;                                   \n"
"            case    9: return  66.63533f;                                   \n"
"            case   10: return  95.10477f;                                   \n"
"            case   11: return 126.26711f;                                   \n"
"            case   12: return 157.66678f;                                   \n"
"            case   13: return 186.96906f;                                   \n"
"            case   14: return 211.81561f;                                   \n"
"            case   15: return 229.84409f;                                   \n"
"            case   16: return 239.00920f;                                   \n"
"            case   17: return 244.51880f;                                   \n"
"            case   18: return 248.55106f;                                   \n"
"            case   19: return 251.45792f;                                   \n"
"            case   20: return 253.30617f;                                   \n"
"            case   21: return 254.38364f;                                   \n"
"            case   22: return 254.87805f;                                   \n"
"            case   23: return 254.50528f;                                   \n"
"            case   24: return 242.28555f;                                   \n"
"            case   25: return 216.25360f;                                   \n"
"            case   26: return 181.10410f;                                   \n"
"            case   27: return 141.51198f;                                   \n"
"            case   28: return 102.12467f;                                   \n"
"            case   29: return  67.43021f;                                   \n"
"            case   30: return  41.82657f;                                   \n"
"            case   31: return  23.33998f;                                   \n"
"            default: return -1.0f;                                          \n"
"        }                                                                   \n"
"                                                                            \n"
"    }                                                                       \n"
"                                                                            \n"
"    float get_green_from_table(size_t id)                                   \n"
"    {                                                                       \n"
"                                                                            \n" 
"        switch(id)                                                          \n"
"        {                                                                   \n"
"            case    0: return   2.24772f;                                   \n"
"            case    1: return   4.38378f;                                   \n"
"            case    2: return   6.41868f;                                   \n"
"            case    3: return  11.69186f;                                   \n"
"            case    4: return  25.28062f;                                   \n"
"            case    5: return  45.46635f;                                   \n"
"            case    6: return  70.00731f;                                   \n"
"            case    7: return  97.07170f;                                   \n"
"            case    8: return 124.60256f;                                   \n"
"            case    9: return 151.26897f;                                   \n"
"            case   10: return 176.37556f;                                   \n"
"            case   11: return 199.12393f;                                   \n"
"            case   12: return 218.84903f;                                   \n"
"            case   13: return 234.93768f;                                   \n"
"            case   14: return 246.77850f;                                   \n"
"            case   15: return 253.58151f;                                   \n"
"            case   16: return 254.53967f;                                   \n"
"            case   17: return 251.94934f;                                   \n"
"            case   18: return 245.78825f;                                   \n"
"            case   19: return 236.19637f;                                   \n"
"            case   20: return 223.36536f;                                   \n"
"            case   21: return 207.15530f;                                   \n"
"            case   22: return 187.81662f;                                   \n"
"            case   23: return 165.01135f;                                   \n"
"            case   24: return 136.81346f;                                   \n"
"            case   25: return 105.00961f;                                   \n"
"            case   26: return  72.90131f;                                   \n"
"            case   27: return  43.46163f;                                   \n"
"            case   28: return  19.82122f;                                   \n"
"            case   29: return   5.26334f;                                   \n"
"            case   30: return   2.20703f;                                   \n"
"            case   31: return   2.29760f;                                   \n"
"            default: return -1.0f;                                          \n"
"        }                                                                   \n"
"                                                                            \n"
"    }                                                                       \n"
"                                                                            \n"
"    float get_blue_from_table(size_t id)                                    \n"
"    {                                                                       \n"
"                                                                            \n" 
"        switch(id)                                                          \n"
"        {                                                                   \n"
"            case    0: return  68.50000f;                                   \n"
"            case    1: return  79.36879f;                                   \n"
"            case    2: return  95.08916f;                                   \n"
"            case    3: return 116.73592f;                                   \n"
"            case    4: return 138.96797f;                                   \n"
"            case    5: return 160.55014f;                                   \n"
"            case    6: return 180.41800f;                                   \n"
"            case    7: return 197.60361f;                                   \n"
"            case    8: return 211.45720f;                                   \n"
"            case    9: return 223.10614f;                                   \n"
"            case   10: return 232.60995f;                                   \n"
"            case   11: return 240.26654f;                                   \n"
"            case   12: return 246.22346f;                                   \n"
"            case   13: return 250.50687f;                                   \n"
"            case   14: return 253.26976f;                                   \n"
"            case   15: return 254.57617f;                                   \n"
"            case   16: return 253.42593f;                                   \n"
"            case   17: return 231.85834f;                                   \n"
"            case   18: return 191.35536f;                                   \n"
"            case   19: return 140.38916f;                                   \n"
"            case   20: return  87.35393f;                                   \n"
"            case   21: return  40.69637f;                                   \n"
"            case   22: return   9.10403f;                                   \n"
"            case   23: return   0.47247f;                                   \n"
"            case   24: return   1.70649f;                                   \n"
"            case   25: return   5.54085f;                                   \n"
"            case   26: return  11.43449f;                                   \n"
"            case   27: return  19.26110f;                                   \n"
"            case   28: return  28.73091f;                                   \n"
"            case   29: return  39.77259f;                                   \n"
"            case   30: return  51.72056f;                                   \n"
"            case   31: return  60.93956f;                                   \n"
"            default: return -1.0f;                                          \n"
"        }                                                                   \n"
"                                                                            \n"
"    }                                                                       \n"
"                                                                            \n"
"    float get_red(double input)                                             \n"
"    {                                                                       \n"
"        float colid = (float)(input * 32.0f);                               \n"
"                                                                            \n"
"        size_t colid1 = (size_t)colid;                                      \n"
"        size_t colid2 = (colid + 1);                                        \n"
"                                                                            \n"
"        if(colid2 == 32) colid2 = 0;                                        \n"
"                                                                            \n"
"        float col2pct = colid - colid1;                                     \n"
"        float col1pct = 1.0f - col2pct;                                     \n"
"                                                                            \n"
"        float col1 = get_red_from_table(colid1);                            \n"
"        float col2 = get_red_from_table(colid2);                            \n"
"                                                                            \n"
"        float col = col1 * col1pct + col2 * col2pct;                        \n"
"                                                                            \n"
"        return col;                                                         \n"
"    }                                                                       \n"
"                                                                            \n" 
"    float get_green(double input)                                           \n"
"    {                                                                       \n"
"        float colid = (float)(input * 32.0f);                               \n"
"                                                                            \n"
"        size_t colid1 = (size_t)colid;                                      \n"
"        size_t colid2 = (colid + 1);                                        \n"
"                                                                            \n"
"        if(colid2 == 32) colid2 = 0;                                        \n"
"                                                                            \n"
"        float col2pct = colid - colid1;                                     \n"
"        float col1pct = 1.0f - col2pct;                                     \n"
"                                                                            \n"
"        float col1 = get_green_from_table(colid1);                          \n"
"        float col2 = get_green_from_table(colid2);                          \n"
"                                                                            \n"
"        float col = col1 * col1pct + col2 * col2pct;                        \n"
"                                                                            \n"
"        return col;                                                         \n"
"    }                                                                       \n"
"                                                                            \n" 
"    float get_blue(double input)                                            \n"
"    {                                                                       \n"
"        float colid = (float)(input * 32.0f);                               \n"
"                                                                            \n"
"        size_t colid1 = (size_t)colid;                                      \n"
"        size_t colid2 = (colid + 1);                                        \n"
"                                                                            \n"
"        if(colid2 == 32) colid2 = 0;                                        \n"
"                                                                            \n"
"        float col2pct = colid - colid1;                                     \n"
"        float col1pct = 1.0f - col2pct;                                     \n"
"                                                                            \n"
"        float col1 = get_blue_from_table(colid1);                           \n"
"        float col2 = get_blue_from_table(colid2);                           \n"
"                                                                            \n"
"        float col = col1 * col1pct + col2 * col2pct;                        \n"
"                                                                            \n"
"        return col;                                                         \n"
"    }                                                                       \n"
"                                                                            \n"
"    __kernel void mandelbrot_noalias(global unsigned char* out,             \n"
"                                     global double* position)               \n"
"    {                                                                       \n"
"                                                                            \n"
"        /* calculating index and position */                                \n"
"        size_t tid = get_global_id(0);                                      \n"
"        size_t size = get_global_size(0);                                   \n"
"                                                                            \n"
"        double startx = position[0];                                        \n"
"        double starty = position[1];                                        \n"
"        double sizex = position[2];                                         \n"
"        double sizey = position[3];                                         \n"
"                                                                            \n"
"        double posx = startx + (sizex * tid) / (size - 1);                  \n"
"        double posy = starty + (sizey * tid) / (size - 1);                  \n"
"                                                                            \n"
"        double mag_square = 0.0;                                            \n"
"        unsigned long iter = 0;                                             \n"
"        double x = 0.0;                                                     \n"
"        double y = 0.0;                                                     \n"
"                                                                            \n"
"        /* const, need to be more usefull */                                \n"
"        unsigned long maxiter = 50000;                                      \n"
"        double bailout = 10000.0;                                           \n"
"                                                                            \n"
"        // main calculation                                                 \n"
"        while(mag_square <= bailout && iter < maxiter)                      \n"
"        {                                                                   \n"
"            double xt = x * x - y * y + posx;                               \n"
"            double yt = 2 * x * y + posy;                                   \n"
"            x = xt;                                                         \n"
"            y = yt;                                                         \n"
"            iter = iter + 1;                                                \n"
"            mag_square = x * x + y * y;                                     \n"
"        }                                                                   \n"
"                                                                            \n"
"        // calculate abs of final number                                    \n"
"        double cabs = sqrt(mag_square);                                     \n"
"                                                                            \n"
"        // precalculate often needed numbers at compile time                \n"
"        double il = 1.0/log(2.0);                                           \n"
"        double lp = log(log(128.0));                                        \n"
"                                                                            \n"
"        // calculate color index                                            \n"
"        double index1 = 0.42 * 0.05 * (iter + il*lp - il * log(log(cabs))); \n"
"        double index = fmod(log(index1+1.0), 1.0);                          \n"
"                                                                            \n"
"        if(iter == maxiter)                                                 \n"
"        {                                                                   \n"
"            out[3*tid + 0] = 0;                                             \n"
"            out[3*tid + 1] = 0;                                             \n"
"            out[3*tid + 2] = 0;                                             \n"
"        }                                                                   \n"
"        else                                                                \n"
"        {                                                                   \n"
"            out[3*tid + 0] = (unsigned char) get_red(index);                \n"
"            out[3*tid + 1] = (unsigned char) get_green(index);              \n"
"            out[3*tid + 2] = (unsigned char) get_blue(index);               \n"
"        }                                                                   \n"
"                                                                            \n"
"    }                                                                       \n"
"                                                                            \n"
"    __kernel void mandelbrot_alias_8x8(global unsigned char* out,           \n"
"                                       global double* position)             \n"
"    {                                                                       \n"
"                                                                            \n"
"        // the local synchronization array                                  \n"
"        __local float local_r[64];                                          \n"
"        __local float local_g[64];                                          \n"
"        __local float local_b[64];                                          \n"
"                                                                            \n"
"        /* calculating index and position */                                \n"
"        // get center pixel id                                              \n"
"        size_t tid = get_group_id(0);                                       \n"
"        size_t size = get_num_groups(0);                                    \n"
"                                                                            \n"
"        // get local worker id                                              \n"
"        size_t worker_id_x = get_local_id(0);                               \n"
"        size_t worker_id_y = get_local_id(1);                               \n"
"                                                                            \n"
"        // read input values                                                \n"
"        double startx = position[0];                                        \n"
"        double starty = position[1];                                        \n"
"        double sizex = position[2];                                         \n"
"        double sizey = position[3];                                         \n"
"                                                                            \n"
"        // calculate center position                                        \n"
"        double poscenterx = startx + (sizex * tid) / (size - 1);            \n"
"        double poscentery = starty + (sizey * tid) / (size - 1);            \n"
"                                                                            \n"
"        // calculate pixel distance                                         \n"
"        double pixdistx = sizex / (size - 1.0);                             \n"
"        double pixdisty = sizey / (size - 1.0);                             \n"
"                                                                            \n"
"        // calculate top left pos                                           \n"
"        double leftx = poscenterx - pixdistx/2.0;                           \n"
"        double lefty = poscentery - pixdisty/2.0;                           \n"
"        double topleftx = leftx + pixdisty/2.0;                             \n"
"        double toplefty = lefty - pixdistx/2.0;                             \n"
"                                                                            \n"
"        // calculate local position                                         \n"
"        double local_pos_x = (worker_id_x + 0.5) / 8.0;                     \n"
"        double local_pos_y = (worker_id_y + 0.5) / 8.0;                     \n"
"                                                                            \n"
"        // calculate local coords                                           \n"
"        double posx = topleftx + local_pos_x * pixdistx                     \n"
"                               - local_pos_y * pixdisty;                    \n"
"        double posy = toplefty + local_pos_x * pixdisty                     \n"
"                               + local_pos_y * pixdistx;                    \n"
"                                                                            \n"
"        /* const, need to be more useful */                                 \n"
"        unsigned long maxiter = 10000;                                      \n"
"        double bailout = 10000.0;                                           \n"
"                                                                            \n"
"        // initialize vars                                                  \n"
"        double mag_square = 0.0;                                            \n"
"        unsigned long iter = 0;                                             \n"
"        double x = 0.0;                                                     \n"
"        double y = 0.0;                                                     \n"
"                                                                            \n"
"        // main calculation                                                 \n"
"        while(mag_square <= bailout && iter < maxiter)                      \n"
"        {                                                                   \n"
"            double xt = x * x - y * y + posx;                               \n"
"            double yt = 2 * x * y + posy;                                   \n"
"            x = xt;                                                         \n"
"            y = yt;                                                         \n"
"            iter = iter + 1;                                                \n"
"            mag_square = x * x + y * y;                                     \n"
"        }                                                                   \n"
"                                                                            \n"
"        // calculate abs of final number                                    \n"
"        double cabs = sqrt(mag_square);                                     \n"
"                                                                            \n"
"        // precalculate often needed numbers at compile time                \n"
"        double il = 1.0/log(2.0);                                           \n"
"        double lp = log(log(128.0));                                        \n"
"                                                                            \n"
"        // calculate color index                                            \n"
"        double index1 = 0.42 * 0.05 * (iter + il*lp - il * log(log(cabs))); \n"
"        double index = fmod(log(index1+1.0), 1.0);                          \n"
"                                                                            \n"
"        // calculate colors                                                 \n"
"        if(iter == maxiter)                                                 \n"
"        {                                                                   \n"
"            local_r[8*worker_id_y + worker_id_x] = 0.0f;                    \n"
"            local_g[8*worker_id_y + worker_id_x] = 0.0f;                    \n"
"            local_b[8*worker_id_y + worker_id_x] = 0.0f;                    \n"
"        }                                                                   \n"
"        else                                                                \n"
"        {                                                                   \n"
"            local_r[8*worker_id_y + worker_id_x] = get_red(index);          \n"
"            local_g[8*worker_id_y + worker_id_x] = get_green(index);        \n"
"            local_b[8*worker_id_y + worker_id_x] = get_blue(index);         \n"
"        }                                                                   \n"
"                                                                            \n"
"        // Wait for other threads to finish                                 \n"
"        barrier(CLK_LOCAL_MEM_FENCE);                                       \n"
"                                                                            \n"
"        // combine all color results                                        \n"
"        if(worker_id_x == 0 && worker_id_y == 0)                            \n"
"        {                                                                   \n"
"                                                                            \n"
"            float sum_r = 0.0f;                                             \n"
"            float sum_g = 0.0f;                                             \n"
"            float sum_b = 0.0f;                                             \n"
"                                                                            \n"
"            for(size_t i = 0; i < 64; i++)                                  \n"
"            {                                                               \n"
"                sum_r += local_r[i];                                        \n"
"                sum_g += local_g[i];                                        \n"
"                sum_b += local_b[i];                                        \n"
"            }                                                               \n"
"                                                                            \n"
"            out[3*tid + 0] = (unsigned char) (sum_r/64.0);                  \n"
"            out[3*tid + 1] = (unsigned char) (sum_g/64.0);                  \n"
"            out[3*tid + 2] = (unsigned char) (sum_b/64.0);                  \n"
"                                                                            \n"
"        }                                                                   \n"
"                                                                            \n"
"    }                                                                       \n"
"                                                                            \n";

#endif

