# Copyright (c) 2015 Martin Stumpf
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

FROM stellargroup/hpx:dev

RUN apt-get update && apt-get install -y amd-opencl-dev                         \
                                         zlib1g-dev                             \
                                         libpng-dev
